language: cpp
sudo: false
env:
  global:
    # github token 
    - secure: eOd7E587x23pubciUUEO3T5jmHph+901Y5/x+Sw9t9X9kpFolJrXIwrkpTffUgrYLls5RJD4+S5Z89idkxLz8RqUEfSwUeewkuNC2Xn1Li/Nw3XRjOiieawbGJ50PAMYO7tS0wbhB11xdfQysM+bMPGh5Xg3SBMSJSrrYGokCw815YidnPbpc1+Em7qBYkStr6t8ILoqVpA469LINkoFBN9UWW3E/5SfwbIbNtValJx+06I6ccWr6HfJkde+VlC+/z6TFOZrdrU05XCbAfVfzLgsUt7uSm2FBi29vdF7H/VghuJAZdQ2B6pBCqJ9INzOHITIZlqinj2swrjhzpiO2CH2eDeRnEkSTJe5wnhig/rqXWcJkItoZbpZQ0w50NvLi4gkDBeR5xTQLQvErF6wPinghkZIymZGDxc5HozV/JJbORbANTHL1UDxRTliD/DNiIew6f0qXUCuxJ8JC6cq8ICzcVTeET/GfMH/vkqqWSoLZJgsvh+CIBN7jB19kVolUPYWjqhFIYm7dCGCAwuIq6guKxiKIUMS8kfXqVkfIqhXZEHiGpJeIno5DW0HBCheVHKp8htvolv5SeBA0VTNGw1/82/k99A6rQ4MJ+e0JPjraOUXQ/8Yn6GyPYcGxVCzSgB0B/dIdevN4Foo9jIA4C/D/twEFWhTeEb9jz7lzlU=
    # twine password.
    - secure: "I8xntw7xref9sXK2zHEIH5kZQ1WmM2SqguEm7S/5e2xjKdVvSuaC7HTbwUKRkFJw6DbWTojLD8OimAuwMFQnsyruLYoo4kyzv8t927P+zqKk1VeRR4D03yMdRJ6XCEQhiKnrnCrVBmwD6cfGsmKyALVp0guIhtK47MAthb7X+PmnoKExWnaMJRvy2NHpwgYbEHJke8j8ect7buDHOuRhWurd9Hc7OpxtY1nECWt6ydw5rfl1Dx7LdUuwxJt+sLtKNTiXty34mgGL3UCmFnDt5WfzVSRnoAh8Pce8nKZaDVagZzvKaFq022NqEThvMIQcFBlSiH1dQVc2sWT8NycZN+pbMwrKFPCt6kazrx5Jr1j1FuFr1Fbmn57uq8wwrH8Z2ursKTXK7lK15lAjaU/RV6y11T7lpx2bHncMGPcBUekinChnmcb4Cj0tYmsfv3YBbSBU/2MHmxAAVGCAmBrK1SLCwDcyQP6bFe/3EUoIrqcqE+G4ypOC9iRwio7xKHyx3J2pHRxFczlFPKqNeGrtSUt6PfxlPYs5EK8N3uYrqJbWMa7jnCGGKtTIlhqgJ+vqm3cbnBVh2+549hgcN1RKeora1G0DCuOXxArnQ97oTc1pDCCVvJLTVOOtdQkjskRhRhGu14SiX//ay3JeZrux+Gr4Uly+UKfuc6nGspJgp+w="

matrix:
  include:
    #- env: PAGMO_PLUGINS_NONFREE_BUILD="manylinux64Py38" DOCKER_IMAGE="pagmo2/manylinux2010_x86_64_with_deps"
    #  sudo: required
    #  services:
    #  - docker
    #- env: PAGMO_PLUGINS_NONFREE_BUILD="manylinux64Py37" DOCKER_IMAGE="pagmo2/manylinux2010_x86_64_with_deps"
    #  sudo: required
    #  services:
    #  - docker
    #- env: PAGMO_PLUGINS_NONFREE_BUILD="manylinux64Py36" DOCKER_IMAGE="pagmo2/manylinux2010_x86_64_with_deps"
    #  sudo: required
    #  services:
    #  - docker
    #- env: PAGMO_PLUGINS_NONFREE_BUILD="DebugGCC"
    #  dist: bionic
    #  compiler: gcc
    #  os: linux
    #  addons:
    #    apt:
    #      sources:
    #      - ubuntu-toolchain-r-test
    #      packages:
    #      - binutils-gold
    #- env: PAGMO_PLUGINS_NONFREE_BUILD="ReleaseGCC"
    #  dist: bionic
    #  compiler: gcc
    #  os: linux
    #  addons:
    #    apt:
    #      sources:
    #      - ubuntu-toolchain-r-test
    #      packages:
    #      - binutils-gold
    #- env: PAGMO_PLUGINS_NONFREE_BUILD="CoverageGCC"
    #  dist: bionic
    #  compiler: gcc
    #  os: linux
    #  addons:
    #    apt:
    #      sources:
    #      - ubuntu-toolchain-r-test
    #      packages:
    #      - binutils-gold
    #- env: PAGMO_PLUGINS_NONFREE_BUILD="ReleaseClang"
    #  dist: bionic
    #  compiler: clang
    #  os: linux
    #  addons:
    #    apt:
    #      sources:
    #      - ubuntu-toolchain-r-test
    #      packages:
    #      - clang-7
    #- env: PAGMO_PLUGINS_NONFREE_BUILD="DebugClang"
    #  dist: bionic
    #  compiler: clang
    #  os: linux
    #  addons:
    #    apt:
    #      sources:
    #      - ubuntu-toolchain-r-test
    #      packages:
    #      - clang-7
    #- env: PAGMO_PLUGINS_NONFREE_BUILD="Python37"
    #  dist: bionic
    #  compiler: gcc
    #  os: linux
    #  addons:
    #    apt:
    #      sources:
    #      - ubuntu-toolchain-r-test
    #- env: PAGMO_PLUGINS_NONFREE_BUILD="OSXDebug"
    #  os: osx
    #- env: PAGMO_PLUGINS_NONFREE_BUILD="OSXRelease"
    #  os: osx
    - env: PAGMO_PLUGINS_NONFREE_BUILD="OSXPython37"
      os: osx
      osx_image: xcode10.3
script:
- mkdir build
- cd build
# NOTE: currently, travis does not stop automatically if one of these
# 2 scripts returns an error code. Thus, we run them together as a single
# command, so that if install_deps.sh fails the whole build fails immediately
# rather than executing install_travis.sh as well. See
# https://github.com/travis-ci/travis-ci/issues/1066
- ../tools/install_deps.sh && ../tools/install_travis.sh
